### ISSUE TITLE
fix my life

### ISSUE THREAD

**Issue by Vilucas** [Vilucas/N-puzzle#17]

**Comment by josecyc** [comment]
this isnt fixed, lucas

**Comment by Vilucas** [comment]
??
Envoyé à partir d’un Smarpthone Android avec GMX Mail.Le 26/09/2019, 21:36 JoseCyC <notifications@github.com> a écrit:
Reopened #17.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Vilucas/N-puzzle/issues/17?email_source=notifications\u0026email_token=AKEGRGFTU35TLGJ6ATC3OYLQLWEWJA5CNFSM4IZY3GI2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOT36OOKA#event-2667374376",
"url": "https://github.com/Vilucas/N-puzzle/issues/17?email_source=notifications\u0026email_token=AKEGRGFTU35TLGJ6ATC3OYLQLWEWJA5CNFSM4IZY3GI2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOT36OOKA#event-2667374376",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Vilucas** [comment]
gl tuesday <3
